### Task1

In [2]:
import numpy as np
def FahToCel(f):
    c=(f-32)*(5/9)
    return c
@np.vectorize
def FahToCel(f):
    c=(f-32)*(5/9)
    return c

temperature_f=np.array([32,68,100,212,77])
temperature_c=FahToCel(temperature_f)
temperature_c



array([  0.        ,  20.        ,  37.77777778, 100.        ,
        25.        ])

### Task2

In [6]:
def cal_pow(num, n):
    return num**n
a=np.array([2,3,4,5])
b=np.array([1,2,3,4])
res=cal_pow(a,b)
print(res)
# ** operation is already vectorized, so no need to vectorize here



array([  2,   9,  64, 625])

### Task3
$$
\begin{cases}
4x+5y+6z=7 \\
3x-y+z=4 \\
2x+y-2z=5
\end{cases}
$$

In [10]:
m=np.array([[4,5,6],
           [3,-1,1],
           [2,1,-2]])
v=np.array([7,4,5])
sol=np.linalg.solve(m,v)
print(sol)


[ 1.7027027   0.62162162 -0.48648649]


### Task4
$$
\begin{cases}
10I_1-2I_2+3I_3=12 \\
-2I_1+8I_2-I_3=-5 \\
3I_1-I_2+6I_3=15
\end{cases}
$$

In [12]:
m=np.array([
    [10,-2,3],
    [-2,8,-1],
    [3,-1,6]
])
v=np.array([12,-5,15])
res=np.linalg.solve(m,v)
print('I1=',res[0])
print('I2=',res[1])
print('I3=',res[2])

I1= 0.48963730569948194
I2= -0.2253886010362694
I3= 2.2176165803108807


### Task5

In [15]:
from PIL import Image

In [19]:
with open('lesson-15/homework/images/birds.jpg') as img:
    print(img.mode)
    img_arr=np.array(img)

FileNotFoundError: [Errno 2] No such file or directory: 'lesson-15/homework/images/birds.jpg'