In [1]:
import numpy as np


1. Create a vector with values ranging from 10 to 49.

In [5]:
v=np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3x3 matrix with values ranging from 0 to 8.

In [11]:
m=np.arange(9).reshape(3,3) #first generate the matrix in given range and reshape it to given shape
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3x3 identity matrix.

In [16]:
i=np.eye(3,3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a 3x3x3 array with random values.

In [20]:
import random
r=np.random.random((3,3,3)) # this gives random matrix, just one object should be given inside the function
r

array([[[0.75927121, 0.74971179, 0.52710183],
        [0.9542625 , 0.32115714, 0.20815502],
        [0.64463151, 0.30087108, 0.22381138]],

       [[0.46013347, 0.49116051, 0.25340444],
        [0.91279214, 0.38577048, 0.69589671],
        [0.57973216, 0.42847908, 0.25326558]],

       [[0.55615452, 0.60751125, 0.00650345],
        [0.41122905, 0.77526959, 0.32792067],
        [0.04549735, 0.35030509, 0.5359219 ]]])

5. Create a 10x10 array with random values and find the minimum and maximum values.

In [22]:
r=np.random.random((10,10))
print(r)
print(np.max(r))
print(np.min(r))


[[0.30174323 0.52733632 0.58044035 0.96118219 0.53424822 0.79186392
  0.81034627 0.65239815 0.44723773 0.33349527]
 [0.55049476 0.81042316 0.5042562  0.64549301 0.19267942 0.32477629
  0.84284766 0.85582442 0.99116832 0.24839985]
 [0.86061499 0.06389256 0.99562477 0.37627018 0.19731972 0.75368846
  0.85866493 0.12933482 0.33198841 0.03511593]
 [0.18583547 0.8521783  0.36263698 0.9151017  0.07551313 0.33472536
  0.48716277 0.39653973 0.48292544 0.57624894]
 [0.9202335  0.52341457 0.18105411 0.61572911 0.20159576 0.12921041
  0.96447484 0.74232348 0.26805052 0.56997752]
 [0.62638258 0.15620089 0.8630547  0.80209844 0.7935845  0.52264429
  0.05153956 0.28224306 0.79719573 0.55227145]
 [0.7478184  0.06012464 0.10169291 0.6614669  0.98444381 0.26125127
  0.33629644 0.78869304 0.91394367 0.96600528]
 [0.38074806 0.65480935 0.47643786 0.25389208 0.54100945 0.19129207
  0.6133469  0.43542668 0.35475039 0.77572595]
 [0.6113112  0.80830342 0.65285531 0.44445844 0.93685743 0.181239
  0.39586317 0

6. Create a random vector of size 30 and find the mean value.

In [25]:
r=np.random.random(30)
print(r)
mean=np.sum(r)/30
print(mean)

[0.39970791 0.21552418 0.65186141 0.45108156 0.51644546 0.21607939
 0.66910678 0.51167762 0.93191284 0.96998927 0.61678802 0.06315801
 0.80135409 0.40131912 0.75722655 0.5850366  0.78511102 0.20903789
 0.34855257 0.0527526  0.91174029 0.9406146  0.61578723 0.51979427
 0.56071841 0.70881785 0.51788993 0.43461384 0.21101181 0.10447984]
0.5226396989068847


7. Normalize a 5x5 random matrix.

In [36]:
r=np.random.random((5,5))
r1=(r*100).astype(int) # this will make it integer
print('Original:\n',r1)
normalized=(r1-np.min(r1))/(np.max(r1)-np.min(r1)) # this will normalize the matrix, scaling its values in range [0,1]
print('Normalized:\n',normalized)

Original:
 [[98 20 29 50 13]
 [89 49 90 78 21]
 [26  4 50 67 59]
 [80 90 20 44 83]
 [ 0 10 50  5 83]]
Normalized:
 [[1.         0.20408163 0.29591837 0.51020408 0.13265306]
 [0.90816327 0.5        0.91836735 0.79591837 0.21428571]
 [0.26530612 0.04081633 0.51020408 0.68367347 0.60204082]
 [0.81632653 0.91836735 0.20408163 0.44897959 0.84693878]
 [0.         0.10204082 0.51020408 0.05102041 0.84693878]]


8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [98]:
r1=np.random.random((5,3))
n1=(r1*10).astype(int)
r2=np.random.random((3,2))
n2=(r2*10).astype(int)

#method1:
#finding using several feature:
print("Matrix n1 (5x3):\n", n1, '\n')
print("Matrix n2 (3x2):\n", n2, '\n')

n3=n2.transpose()
n4=[i*n1 for i in n3] # list of two matrices
n5=[i.transpose() for i in n4] # list of two transposed matrices
m1=n5[0][0]+n5[0][1]+n5[0][2]
m2=n5[1][0]+n5[1][1]+n5[1][2]
arr=np.vstack((m1,m2)) # this will make two arrays just one array
print("Result of n1 @ n2 (5x2):\n", arr.transpose())

#method2:
#finding using just one function:
result = np.dot(n1, n2)

print("Matrix n1 (5x3):\n", n1, '\n')
print("Matrix n2 (3x2):\n", n2, '\n')
print("Result of n1 @ n2 (5x2):\n", result)






Matrix n1 (5x3):
 [[8 8 0]
 [3 1 6]
 [6 1 3]
 [5 2 2]
 [7 7 4]] 

Matrix n2 (3x2):
 [[7 3]
 [1 7]
 [2 3]] 

Result of n1 @ n2 (5x2):
 [[64 80]
 [34 34]
 [49 34]
 [41 35]
 [64 82]]


In [99]:
#method2:
#finding using just one function:
result = np.dot(n1, n2)

print("Matrix n1 (5x3):\n", n1, '\n')
print("Matrix n2 (3x2):\n", n2, '\n')
print("Result of n1 @ n2 (5x2):\n", result)


Matrix n1 (5x3):
 [[8 8 0]
 [3 1 6]
 [6 1 3]
 [5 2 2]
 [7 7 4]] 

Matrix n2 (3x2):
 [[7 3]
 [1 7]
 [2 3]] 

Result of n1 @ n2 (5x2):
 [[64 80]
 [34 34]
 [49 34]
 [41 35]
 [64 82]]


9. Create two 3x3 matrices and compute their dot product.

In [92]:
m1=np.random.random((3,3))
m11=(m1*10).astype(int)
m2=np.random.random((3,3))
m22=(m2*10).astype(int)
res=np.dot(m11,m22) # their dot product
print("Matrix 1 (3x3):\n", m11, '\n')
print("Matrix 2 (3x3):\n", m22, '\n')
print("Dot product:\n", res)


Matrix 1 (3x3):
 [[7 8 9]
 [2 2 7]
 [5 1 9]] 

Matrix 2 (3x3):
 [[6 1 3]
 [8 8 9]
 [5 8 2]] 

Dot product:
 [[151 143 111]
 [ 63  74  38]
 [ 83  85  42]]


10. Given a 4x4 matrix, find its transpose.

In [95]:
m=np.random.random((4,4))
m1=(m*10).astype(int)
trans=m1.transpose() # transpose of it
print("Matrix:\n", m1)
print("Its transpose:\n", trans)

Matrix:
 [[5 2 0 1]
 [1 6 2 3]
 [3 6 0 0]
 [4 4 0 6]]
Its transpose:
 [[5 1 3 4]
 [2 6 6 4]
 [0 2 0 0]
 [1 3 0 6]]


11. Create a 3x3 matrix and calculate its determinant.

In [114]:
m=np.random.random((3,3))
m1=(m*10).astype(int)
print(m1)
def cal_det_two(matrix):
    det=matrix[0,0]*matrix[1,1]-matrix[0,1]*matrix[1,0]
    return det
first=m1[[1,2]][:,[1,2]]
second=m1[[1,2]][:,[0,2]]
third=m1[[1,2]][:,[0,1]]
det=m1[0,0]*cal_det_two(first)-m1[0,1]*cal_det_two(second)+m1[0,2]*cal_det_two(third)
print("Determinant:", det)


[[3 0 1]
 [0 5 1]
 [6 4 1]]
Determinant: -27


12. Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

In [116]:
A=np.random.random((3,4))
A1=(A*10).astype(int)
B=np.random.random((4,3))
B1=(B*10).astype(int)
dot=np.dot(A1,B1)
print("A:\n", A1)
print("B:\n",B1)
print("Dot product:\n", dot)

A:
 [[2 3 8 0]
 [1 6 9 2]
 [1 9 1 5]]
B:
 [[5 4 7]
 [8 2 4]
 [1 7 1]
 [5 5 6]]
Dot product:
 [[ 42  70  34]
 [ 72  89  52]
 [103  54  74]]


13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

In [124]:
A=np.random.random((3,3))
A1=(A*10).astype(int)
B=np.random.random((3,1))
B1=(B*10).astype(int)
dot=np.dot(A1,B1)
print("A:\n", A1)
print("B:\n",B1)
print("Dot product:\n", dot)

A:
 [[2 4 8]
 [7 1 2]
 [3 1 8]]
B:
 [[2]
 [7]
 [5]]
Dot product:
 [[72]
 [31]
 [53]]


14. Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.

In [125]:
A=np.random.random((3,3))
A1=(A*10).astype(int)
B=np.random.random((3,1))
B1=(B*10).astype(int)
x=np.linalg.solve(A1,B1)
print("A:\n", A1)
print("B:\n",B1)
print("Solution of Ax=b:\n", x)

A:
 [[0 2 6]
 [6 6 3]
 [1 3 5]]
B:
 [[2]
 [2]
 [9]]
Solution of Ax=b:
 [[-11.77777778]
 [ 14.33333333]
 [ -4.44444444]]


15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [129]:
A=np.random.random((5,5))
A1=(A*10).astype(int)
row_wise=np.sum(A1, axis=1)
col_wise=np.sum(A1,axis=0)
print("Matrix:\n",A1)
print("Row-wise:\n",row_wise)
print("col-wise:\n",col_wise)

Matrix:
 [[7 1 4 0 8]
 [9 6 2 8 1]
 [9 6 5 1 2]
 [5 8 0 3 1]
 [2 4 0 0 4]]
Row-wise:
 [20 26 23 17 10]
col-wise:
 [32 25 11 12 16]


In [135]:
with open('sample1.txt','r') as file:
    content=file.read()
content


''