### Task1

In [2]:
import numpy as np
def FahToCel(f):
    c=(f-32)*(5/9)
    return c
@np.vectorize
def FahToCel(f):
    c=(f-32)*(5/9)
    return c

temperature_f=np.array([32,68,100,212,77])
temperature_c=FahToCel(temperature_f)
temperature_c



array([  0.        ,  20.        ,  37.77777778, 100.        ,
        25.        ])

### Task2

In [6]:
def cal_pow(num, n):
    return num**n
a=np.array([2,3,4,5])
b=np.array([1,2,3,4])
res=cal_pow(a,b)
print(res)
# ** operation is already vectorized, so no need to vectorize here



array([  2,   9,  64, 625])

### Task3
$$
\begin{cases}
4x+5y+6z=7 \\
3x-y+z=4 \\
2x+y-2z=5
\end{cases}
$$

In [10]:
m=np.array([[4,5,6],
           [3,-1,1],
           [2,1,-2]])
v=np.array([7,4,5])
sol=np.linalg.solve(m,v)
print(sol)


[ 1.7027027   0.62162162 -0.48648649]


### Task4
$$
\begin{cases}
10I_1-2I_2+3I_3=12 \\
-2I_1+8I_2-I_3=-5 \\
3I_1-I_2+6I_3=15
\end{cases}
$$

In [12]:
m=np.array([
    [10,-2,3],
    [-2,8,-1],
    [3,-1,6]
])
v=np.array([12,-5,15])
res=np.linalg.solve(m,v)
print('I1=',res[0])
print('I2=',res[1])
print('I3=',res[2])

I1= 0.48963730569948194
I2= -0.2253886010362694
I3= 2.2176165803108807


### Task5

In [15]:
from PIL import Image

In [66]:
with Image.open('images/birds.jpg') as img:
    print(img.mode)
    img_arr=np.array(img)

RGB


In [31]:
flipped=img_arr[::-1, ::-1,:]
flipped
flipped_img=Image.fromarray(flipped, mode='RGB')
flipped_img.save('images/flipped.jpg')

In [48]:
noise=np.random.normal(0,30,img_arr.shape) # this will generate a random array in the shape of img_arr
noisy_img_arr=img_arr+noise # adding the two arrays
noisy_img_arr=np.clip(noisy_img_arr, 0, 255) # giving range to values of array
noisy_img=Image.fromarray(noisy_img_arr.astype(np.uint8)) # making values 8 bit integer
noisy_img.save('images/noisy_img.jpg')


In [56]:
brithen_arr=(img_arr[:,:,2]+30)
brithen_arr=np.clip(brithen_arr, 0, 255)
brithen_img=Image.fromarray(brithen_arr)
brithen_img.save('images/brithen_img.jpg')

In [73]:
masked=img_arr.copy()
masked[360-50:360+50,360-50:360+50,:]=0
img_rec=Image.fromarray(masked)
img_rec.save('images/rectangle.jpg')



### Bonus challenges

In [67]:
def flip_img(img):
    arr=np.array(img)
    flipped=arr[::-1, ::-1, :]
    flipped_img=Image.fromarray(flipped)
    return flipped_img

In [68]:
def add_noise(img, std):
    arr=np.array(img)
    noise=np.random.normal(0,std,arr.shape)
    noisy=arr+noise
    noisy=np.clip(noisy, 0, 255)
    noisy_img=Image.fromarray(noisy.astype(np.uint8))
    return noisy_img


In [69]:
def brithen_channels(img, num):
    arr=np.array(img)
    brithen=arr[:,:,:]+num
    brithen=np.clip(brithen, 0, 255)
    brithen_img=Image.fromarray(brithen)
    return brithen_img


In [74]:
def apply_mask(img, size):
    arr=np.array(img)
    height, width, _=img.shape
    startx=(width-size[1])//2
    starty=(height-size[0])//2
    endx=startx+size[1]
    endy=starty+size[0]
    masked=arr.copy()
    masked[starty:endy, startx:endx, :]=[0,0,0]
    masked_img=Image.fromarray(masked_img)
    return masked_img    
    